### ISSUE TITLE
Laravel 9 Desteği

### ISSUE THREAD

**Issue by victorioustr** [herkod/laravel-tr#2]
Laravel 9 için paketi güncelleyebilir misin.

**Comment by evrend** [comment]
Laravel 9 için eklenmesi ve güncellenmesi gereken çevirilerin kontrol edilmesi gerekiyor. Gerekli çalışma yapıldıktan sonra Laravel 9 desteği eklenecektir.

**Comment by victorioustr** [comment]
teşekkürler. bekliyoruz.

**Comment by evrend** [comment]
Laravel 9 için gerekli geliştirmeleri yaparak yayınladık. Laravel 9 desteği için paketin **v2.*** versiyonlarını kullanabilirsiniz.

https://github.com/herkod/laravel-tr/releases/tag/v2.0.1

Bu versiyondaki katkıları için @ouzkilic 'a teşekkürler.
