### ISSUE TITLE
Laravel 9 lang dizini değişti.

### ISSUE THREAD

**Issue by fatihdurmaz** [herkod/laravel-tr#4]
Merhaba Laravel 9 ile resources/lang dizini, ana dizine lang olarak taşındı. paketin klasör yolunu güncelleyebilir misiniz?

<?php

namespace Herkod;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->publishes([
            __DIR__.'/../lang/' => lang_path()
        ], 'herkod-laravel-tr');
    }
}

**Comment by evrend** [comment]
**Laravel 9**'da varsayılan lang klasörü ana dizindeki `Lang` klasörüdür. `lang_path()` methodu varsayılan olarak bu klasörü döndürüyor. Bizde dil dosyalarını publish ederken bu methodu kullanıyoruz. Fakat `resources/lang` klasörü varsa, herhangi bir şekilde oluşturduysanız `lang_path()` methodu bu klasörü döndürmektedir. Geriye dönük uyumluluk olması açısından böyle yaptıklarını düşünüyorum.
**Sonuç olarak:** `resources/lang` klasörünün var olup olmadığını kontrol etmenizi ve varsa silerek denemenizi tavsiye ederim.

**Comment by fatihdurmaz** [comment]
Deneyimleyip, buradan diğer kullanıcıların da bilgisi sahibi olması için paylaşacağım. Teşekkür ederim.
